### ISSUE TITLE
UserExportSerializer incompatible with v0.27.0

### ISSUE THREAD

**Issue by Quentinchampenois** [PopulateTools/decidim-module-extra_user_fields#11]
#### Description

I tried to run tests on v0.27.0 version of Decidim and I found that exports are not working. 

The class `Decidim::DataPortabilitySerializers::DataPortabilityUserSerializer` is no longer existing on v0.27.0 and has been renamed.

#### Environment

* Decidim v0.27.0
* Ruby version: 3.0.2

#### Stacktrace

```
An error occurred while loading ./spec/serializers/user_export_serializer_spec.rb.
Failure/Error:
      class UserExportSerializer < Decidim::DataPortabilitySerializers::DataPortabilityUserSerializer
        # Public: Exports a hash with the serialized data for the user including
        # extra user fields
        def serialize
          super.merge(extra_user_fields)
        end
  
        def extra_user_fields
          extended_data = resource.extended_data.symbolize_keys
  

NameError:
  uninitialized constant Decidim::DataPortabilitySerializers
# ./app/serializers/decidim/extra_user_fields/user_export_serializer.rb:6:in `<module:ExtraUserFields>'
# ./app/serializers/decidim/extra_user_fields/user_export_serializer.rb:5:in `<module:Decidim>'
# ./app/serializers/decidim/extra_user_fields/user_export_serializer.rb:3:in `<main>'
# ./spec/serializers/user_export_serializer_spec.rb:5:in `<main>'
```

#### Related to

* Issue: [9169](https://github.com/decidim/decidim/issues/9169)
* Pull request : [9196](https://github.com/decidim/decidim/pull/9196)

**Comment by flogee** [comment]
Does it work with later versions than 0.27?

**Comment by ArthurJahn** [comment]
This issue should be closed. The PR #16 fixes the error

**Comment by furilo** [comment]
great, thanks!
